version: '3.8'
networks:
    not-so-simple-ecommerce:
        driver: bridge
        
services:
    # not-so-simple-ecommerce.site:
    #   container_name: not-so-simple-ecommerce-site
    #   image: not-so-simple-ecommerce/not-so-simple-ecommerce-site
    #   build:
    #     context: src/frontend
    #     dockerfile: Dockerfile.dev
    #   volumes:
    #     - ./src/frontend:/app
    #   ports:
    #     - "3000:3000"
    #   networks:
    #       - not-so-simple-ecommerce

    # not-so-simple-ecommerce.nginx:
    #   container_name: not-so-simple-ecommerce-lb
    #   image: nginx:1.20.2
    #   volumes:
    #     - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    #     - "${NGINX_CERTIFICATES_PATH}:/etc/nginx/certs:ro"
    #   ports:
    #     - "44300:44300"
    #   networks:
    #       - not-so-simple-ecommerce
          
    # not-so-simple-ecommerce.db:
    #     container_name: not-so-simple-ecommerce-db
    #     image: postgres:10.14
    #     ports:
    #         - '5432:5432'
    #     networks:
    #         - not-so-simple-ecommerce
    #     env_file:
    #       - ./.env

    not-so-simple-ecommerce.main:
        container_name: not-so-simple-ecommerce-main
        image: not-so-simple-ecommerce/not-so-simple-ecommerce-main
        ports:
          - '5000:443'
        build:
          context: .
          dockerfile: src/services/NotSoSimpleEcommerce.Main/Dockerfile
        networks:
            - not-so-simple-ecommerce
        env_file:
          - ./.env
        volumes:
          - ${CERTIFICATES_HOST_PATH}:${CERTIFICATES_CONTAINER_PATH}:ro
          - ${AWS_CREDENTIALS_HOST_PATH}:${AWS_CREDENTIALS_CONTAINER_PATH}:ro

    # not-so-simple-ecommerce.health-checker:
    #     container_name: not-so-simple-ecommerce-health-checker
    #     image: not-so-simple-ecommerce/not-so-simple-ecommerce-health-checker
    #     ports:
    #       - "5001:443"
    #     build:
    #       context: .
    #       dockerfile: src/services/NotSoSimpleEcommerce.HealthChecker/Dockerfile
    #     networks:
    #         - not-so-simple-ecommerce
    #     env_file:
    #       - ./.env
    #     volumes:
    #       - ${CERTIFICATES_HOST_PATH}:${CERTIFICATES_CONTAINER_PATH}:ro
    #       - ${AWS_CREDENTIALS_HOST_PATH}:${AWS_CREDENTIALS_CONTAINER_PATH}:ro

    not-so-simple-ecommerce.order:
        container_name: not-so-simple-ecommerce-order
        image: not-so-simple-ecommerce/not-so-simple-ecommerce-order
        ports:
          - "5002:443"
        build:
          context: .
          dockerfile: src/services/NotSoSimpleEcommerce.Order/Dockerfile
        networks:
            - not-so-simple-ecommerce
        env_file:
          - ./.env
        volumes:
          - ${CERTIFICATES_HOST_PATH}:${CERTIFICATES_CONTAINER_PATH}:ro
          - ${AWS_CREDENTIALS_HOST_PATH}:${AWS_CREDENTIALS_CONTAINER_PATH}:ro

    # not-so-simple-ecommerce.notificator:
    #   container_name: not-so-simple-ecommerce-notificator
    #   image: not-so-simple-ecommerce/not-so-simple-ecommerce-notificator
    #   ports:
    #     - "5003:443"
    #   build:
    #     context: .
    #     dockerfile: src/workers/NotSoSimpleEcommerce.Notificator/Dockerfile
    #   networks:
    #     - not-so-simple-ecommerce
    #   env_file:
    #     - ./.env
    #   volumes:
    #     - ${CERTIFICATES_HOST_PATH}:${CERTIFICATES_CONTAINER_PATH}:ro
    #     - ${AWS_CREDENTIALS_HOST_PATH}:${AWS_CREDENTIALS_CONTAINER_PATH}:ro

    not-so-simple-ecommerce.identity-server:
      container_name: not-so-simple-ecommerce-identity-server
      image: not-so-simple-ecommerce/not-so-simple-ecommerce-identity-server
      ports:
        - "5004:443"
      build:
        context: .
        dockerfile: src/services/NotSoSimpleEcommerce.IdentityServer/Dockerfile
      networks:
        - not-so-simple-ecommerce
      env_file:
        - ./.env
      volumes:
        - ${CERTIFICATES_HOST_PATH}:${CERTIFICATES_CONTAINER_PATH}:ro
        - ${AWS_CREDENTIALS_HOST_PATH}:${AWS_CREDENTIALS_CONTAINER_PATH}:ro

    # not-so-simple-ecommerce.invoice-generator:
    #   container_name: not-so-simple-ecommerce-invoice-generator
    #   image: not-so-simple-ecommerce/not-so-simple-ecommerce-invoice-generator
    #   ports:
    #     - "5005:443"
    #   build:
    #     context: .
    #     dockerfile: src/workers/NotSoSimpleEcommerce.InvoiceGenerator/Dockerfile
    #   networks:
    #     - not-so-simple-ecommerce
    #   env_file:
    #     - ./.env
    #   volumes:
    #     - ${CERTIFICATES_HOST_PATH}:${CERTIFICATES_CONTAINER_PATH}:ro
    #     - ${AWS_CREDENTIALS_HOST_PATH}:${AWS_CREDENTIALS_CONTAINER_PATH}:ro